apiVersion: v1
kind: Service
metadata:
  name: tictac-api
  labels:
    name: tictac-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: tictac
